---
- name: Set up Docker and Nginx container
  hosts: web
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    use_backend: dnf4  # Set backend version
    pkg_mgr: dnf4      # Explicitly specify the package manager

  tasks:
    - name: Ensure Python `pip` is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install specific versions of requests and urllib3
      ansible.builtin.pip:
        name:
          - requests==2.28.1   # Compatible with older urllib3
          - urllib3==1.26.5    # Compatible with OpenSSL 1.0.2k
        executable: /usr/bin/pip3

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Ensure Nginx container is running
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
