---
- name: Set up Docker and Nginx container
  hosts: all  # Apply to any hosts specified in the command
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure python3-apt is installed (required for apt module)
      raw: sudo apt-get update && sudo apt-get install -y python3-apt
      changed_when: false

    - name: Ensure Python `pip` is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install specific versions of requests and urllib3
      ansible.builtin.pip:
        name:
          - requests==2.28.1   # Compatible with older urllib3
          - urllib3==1.26.5    # Compatible with OpenSSL 1.0.2k
        executable: /usr/bin/pip3

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: ubuntu  # Adjust to your instance's user if different
        groups: docker
        append: yes

    - name: Ensure Nginx container is running
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
