---
- name: Set up Docker and Nginx container
  hosts: web
  become: yes
  tasks:
    - name: Ensure Python 3 and pip are installed
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install specific versions of requests and urllib3 via pip
      pip:
        name:
          - requests==2.28.1
          - urllib3==1.26.5
        executable: /usr/bin/pip3

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Nginx container using Docker
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
