---
- name: Set up Docker and Nginx container
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure python3-apt is installed (required for apt module)
      raw: sudo apt-get update && sudo apt-get install -y python3-apt
      changed_when: false

    - name: Ensure Python `pip` is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install specific versions of requests and urllib3
      ansible.builtin.pip:
        name:
          - requests==2.28.1
          - urllib3==1.26.5
        executable: /usr/bin/pip3

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create a directory for index.html
      file:
        path: /home/ubuntu/nginx-html
        state: directory

    - name: Copy index.html to Nginx directory
      copy:
        src: ./index.html
        dest: /home/ubuntu/nginx-html/index.html

    - name: Run Nginx container with custom index.html
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/nginx-html:/usr/share/nginx/html:ro
