name: CI/CD Pipeline with Terraform, Ansible, and Docker

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS credentials for use in Terraform and Ansible
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Remove existing Docker and containerd dependencies if any
      - name: Remove existing Docker and containerd dependencies
        run: |
          sudo apt-get remove --purge -y docker docker-engine docker.io containerd runc containerd.io
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/docker
          sudo rm -rf /var/lib/containerd
          sudo rm -rf /etc/docker
          sudo rm -rf /etc/containerd

      # Install Docker using the official convenience script
      - name: Install Docker using the official convenience script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # Verify Docker Installation
      - name: Verify Docker Installation
        run: sudo docker --version

      # Initialize Terraform and apply configuration to provision EC2 instance
      - name: Terraform Initialize and Apply
        run: |
          terraform init
          terraform apply -auto-approve

      # Retrieve EC2 public IP from Terraform output
      - name: Retrieve EC2 Public IP
        id: ec2_ip
        run: echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      # Set up SSH private key and disable host key checking
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > my-key-pair.pem
          chmod 600 my-key-pair.pem
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" > ~/.ssh/config

      # Add a wait time to ensure EC2 instance is ready
      - name: Wait for EC2 instance to be ready
        run: sleep 300

      # Run the Ansible playbook with inline inventory using the retrieved EC2 IP
      - name: Run Ansible playbook
        run: |
          ansible-playbook playbook.yml \
            -i "${{ env.EC2_PUBLIC_IP }}," \
            -e "ansible_user=ubuntu" \
            -e "ansible_host=${{ env.EC2_PUBLIC_IP }}" \
            -e "ansible_ssh_private_key_file=my-key-pair.pem" \
            -e "ansible_python_interpreter=/usr/bin/python3"
